"""Repository interfaces used by the application services.

Services depend only on these protocols (through `UnitOfWork`); the SQLAlchemy
implementations in `sql.py` are the only code that performs persistence.
Entities are the mapped classes in `app.models`; changes made to an entity
returned by a repository are persisted when the unit of work commits.
"""

import uuid
from collections.abc import Iterable, Sequence
from datetime import datetime
from typing import Any, Protocol

from app import models as m
from app.pagination import Page, PageRequest


class DuplicateError(Exception):
    """A unique constraint rejected the write (e.g. a concurrent duplicate)."""


class UserRepository(Protocol):
    def add(self, user: m.User) -> m.User: ...
    def get(self, user_id: uuid.UUID) -> m.User | None: ...
    def get_by_email(self, email: str) -> m.User | None: ...


class SessionRepository(Protocol):
    def add(self, session: m.Session) -> m.Session: ...
    def get_by_token_hash(self, token_hash: str) -> m.Session | None: ...
    def revoke_for_users(self, user_ids: Iterable[uuid.UUID], now: datetime) -> int: ...
    def delete_expired_before(self, before: datetime) -> int: ...


class EmailTokenRepository(Protocol):
    def add(self, token: m.EmailToken) -> m.EmailToken: ...
    def get_by_hash(self, token_hash: str, purpose: str, *, for_update: bool = False) -> m.EmailToken | None: ...
    def invalidate_for_user(self, user_id: uuid.UUID, purpose: str, now: datetime) -> None: ...
    def delete_expired_before(self, before: datetime) -> int: ...


class AccountRepository(Protocol):
    def add(self, account: m.Account) -> m.Account: ...
    def get(self, account_id: uuid.UUID, *, for_update: bool = False) -> m.Account | None: ...
    def list_for_user(self, user_id: uuid.UUID) -> list[tuple[m.Account, str]]: ...
    def list_page(self, page: PageRequest) -> Page[m.Account]: ...
    def deleted_before(self, before: datetime) -> list[m.Account]: ...


class MembershipRepository(Protocol):
    def add(self, membership: m.Membership) -> m.Membership: ...
    def get(self, account_id: uuid.UUID, user_id: uuid.UUID, *, for_update: bool = False) -> m.Membership | None: ...
    def list_for_account(self, account_id: uuid.UUID, page: PageRequest) -> Page[tuple[m.Membership, m.User]]: ...
    def list_user_ids(self, account_id: uuid.UUID) -> list[uuid.UUID]: ...
    def count_owners(self, account_id: uuid.UUID) -> int: ...
    def delete(self, membership: m.Membership) -> None: ...
    def delete_all_for_account(self, account_id: uuid.UUID) -> None: ...


class InvitationRepository(Protocol):
    def add(self, invitation: m.Invitation) -> m.Invitation: ...
    def get(self, invitation_id: uuid.UUID, account_id: uuid.UUID) -> m.Invitation | None: ...
    def get_by_hash(self, token_hash: str, *, for_update: bool = False) -> m.Invitation | None: ...
    def list_pending(self, account_id: uuid.UUID, now: datetime, page: PageRequest) -> Page[m.Invitation]: ...


class ApiKeyRepository(Protocol):
    def add(self, key: m.ApiKey) -> m.ApiKey: ...
    def get(self, key_id: uuid.UUID, account_id: uuid.UUID) -> m.ApiKey | None: ...
    def get_by_hash(self, key_hash: str) -> m.ApiKey | None: ...
    def list_page(self, account_id: uuid.UUID, page: PageRequest) -> Page[m.ApiKey]: ...
    def revoke_all(self, account_id: uuid.UUID, now: datetime) -> int: ...


class DomainRepository(Protocol):
    def add(self, domain: m.Domain) -> m.Domain: ...
    def get(self, domain_id: uuid.UUID, account_id: uuid.UUID) -> m.Domain | None: ...
    def get_live_by_name(self, name: str) -> m.Domain | None: ...
    def list_page(self, account_id: uuid.UUID, page: PageRequest) -> Page[m.Domain]: ...
    def list_all_for_account(self, account_id: uuid.UUID) -> list[m.Domain]: ...
    def list_due_for_recheck(self, checked_before: datetime, limit: int) -> list[m.Domain]: ...


class DkimKeyRepository(Protocol):
    def add(self, key: m.DkimKey) -> m.DkimKey: ...
    def list_for_domain(self, domain_id: uuid.UUID) -> list[m.DkimKey]: ...
    def list_signing(self) -> list[tuple[m.DkimKey, m.Domain]]: ...
    def delete_retired_before(self, before: datetime) -> int: ...


class SenderIdentityRepository(Protocol):
    def add(self, identity: m.SenderIdentity) -> m.SenderIdentity: ...
    def get(self, identity_id: uuid.UUID, account_id: uuid.UUID) -> m.SenderIdentity | None: ...
    def get_by_email(self, account_id: uuid.UUID, email: str) -> m.SenderIdentity | None: ...
    def list_page(self, account_id: uuid.UUID, page: PageRequest) -> Page[m.SenderIdentity]: ...
    def list_for_domain(self, domain_id: uuid.UUID) -> list[m.SenderIdentity]: ...
    def list_all_for_account(self, account_id: uuid.UUID) -> list[m.SenderIdentity]: ...


class AssetRepository(Protocol):
    def add(self, asset: m.Asset) -> m.Asset: ...
    def get(self, asset_id: uuid.UUID, account_id: uuid.UUID) -> m.Asset | None: ...
    def list_ready(self, account_id: uuid.UUID, page: PageRequest) -> Page[m.Asset]: ...
    def list_all_for_account(self, account_id: uuid.UUID) -> list[m.Asset]: ...
    def list_stale_pending(self, before: datetime, limit: int) -> list[m.Asset]: ...


class MessageRepository(Protocol):
    def add(self, message: m.Message) -> m.Message: ...
    def get(self, message_id: uuid.UUID, account_id: uuid.UUID) -> m.Message | None: ...
    def get_by_idempotency_key(self, account_id: uuid.UUID, key: str) -> m.Message | None: ...
    def list_page(self, account_id: uuid.UUID, page: PageRequest) -> Page[m.Message]: ...
    def add_recipient(self, recipient: m.MessageRecipient) -> m.MessageRecipient: ...
    def get_recipient(self, recipient_id: uuid.UUID, *, for_update: bool = False) -> m.MessageRecipient | None: ...
    def get_message_by_id(self, message_id: uuid.UUID) -> m.Message | None: ...
    def list_recipients(self, message_id: uuid.UUID) -> list[m.MessageRecipient]: ...
    def count_recipients_since(self, account_id: uuid.UUID, since: datetime) -> int: ...
    def count_accepted_since(self, account_id: uuid.UUID, since: datetime) -> int: ...
    def fail_pending_for_account(self, account_id: uuid.UUID, reason: str, now: datetime) -> int: ...
    def list_for_export(self, account_id: uuid.UUID, limit: int) -> list[tuple[m.Message, list[m.MessageRecipient]]]: ...
    def purge_content_before(self, before: datetime, now: datetime) -> int: ...
    def delete_before(self, before: datetime) -> int: ...


class OutboxRepository(Protocol):
    def add(self, event: m.OutboxEvent) -> m.OutboxEvent: ...
    def claim(self, now: datetime, limit: int) -> list[m.OutboxEvent]: ...
    def cancel_for_account(self, account_id: uuid.UUID) -> int: ...
    def delete_processed_before(self, before: datetime) -> int: ...
    def count_by_status(self) -> dict[str, int]: ...


class DeliveryRepository(Protocol):
    def add_attempt(self, attempt: m.DeliveryAttempt) -> m.DeliveryAttempt: ...
    def add_event(self, event: m.DeliveryEvent) -> m.DeliveryEvent: ...
    def count_soft_bounces(self, account_id: uuid.UUID, email: str, since: datetime) -> int: ...
    def count_events_since(self, account_id: uuid.UUID, since: datetime) -> dict[str, int]: ...
    def delete_before(self, before: datetime) -> int: ...


class SuppressionRepository(Protocol):
    def get(self, account_id: uuid.UUID, email: str) -> m.Suppression | None: ...
    def add_if_absent(self, suppression: m.Suppression) -> tuple[m.Suppression, bool]: ...
    def suppressed_among(self, account_id: uuid.UUID, emails: Sequence[str]) -> set[str]: ...
    def list_page(self, account_id: uuid.UUID, page: PageRequest) -> Page[m.Suppression]: ...
    def list_all_for_account(self, account_id: uuid.UUID) -> list[m.Suppression]: ...
    def delete(self, suppression: m.Suppression) -> None: ...


class AuditRepository(Protocol):
    def add(self, event: m.AuditEvent) -> m.AuditEvent: ...
    def list_page(
        self,
        account_id: uuid.UUID,
        page: PageRequest,
        *,
        target_type: str | None = None,
        target_id: uuid.UUID | None = None,
    ) -> Page[m.AuditEvent]: ...
    def latest_for_account(self, account_id: uuid.UUID, actions: Sequence[str]) -> m.AuditEvent | None: ...


class RateLimitRepository(Protocol):
    def hit(self, key: str, window_start: datetime, amount: int = 1) -> int: ...
    def delete_before(self, before: datetime) -> int: ...


class SyncRepository(Protocol):
    def lock_account(self, account_id: uuid.UUID) -> None: ...
    def next_seq(self) -> int: ...
    def get(self, account_id: uuid.UUID, collection: str, record_id: uuid.UUID) -> m.SyncRecord | None: ...
    def add(self, record: m.SyncRecord) -> m.SyncRecord: ...
    def snapshot(
        self, account_id: uuid.UUID, collections: Sequence[str], after: tuple[str, uuid.UUID] | None, limit: int
    ) -> list[m.SyncRecord]: ...
    def changes(self, account_id: uuid.UUID, since: int, limit: int) -> list[m.SyncRecord]: ...
    def max_seq(self, account_id: uuid.UUID) -> int: ...
    def list_children(
        self, account_id: uuid.UUID, collection: str, parent_id: uuid.UUID, page: PageRequest
    ) -> Page[m.SyncRecord]: ...
    def list_all_for_account(self, account_id: uuid.UUID) -> list[m.SyncRecord]: ...
    def delete_all_for_account(self, account_id: uuid.UUID) -> int: ...
    def list_with_objects(self, collection: str, limit: int) -> list[m.SyncRecord]: ...
    def list_inline(self, collection: str, limit: int) -> list[m.SyncRecord]: ...
    def add_upload(self, upload: m.SyncUpload) -> m.SyncUpload: ...
    def get_upload(self, upload_id: uuid.UUID, account_id: uuid.UUID) -> m.SyncUpload | None: ...
    def delete_upload(self, upload: m.SyncUpload) -> None: ...
    def list_uploads_for_account(self, account_id: uuid.UUID) -> list[m.SyncUpload]: ...
    def list_expired_uploads(self, before: datetime, limit: int) -> list[m.SyncUpload]: ...


class ExportRepository(Protocol):
    def add(self, export: m.AccountExport) -> m.AccountExport: ...
    def get(self, export_id: uuid.UUID, account_id: uuid.UUID) -> m.AccountExport | None: ...
    def get_by_id(self, export_id: uuid.UUID) -> m.AccountExport | None: ...
    def list_page(self, account_id: uuid.UUID, page: PageRequest) -> Page[m.AccountExport]: ...
    def list_expired(self, now: datetime) -> list[m.AccountExport]: ...


class JobRepository(Protocol):
    def try_lock(self, name: str) -> bool: ...
    def record(self, name: str, started_at: datetime, finished_at: datetime, error: str | None) -> None: ...
    def list_runs(self) -> list[m.JobRun]: ...


class UnitOfWork(Protocol):
    @property
    def users(self) -> UserRepository: ...

    @property
    def sessions(self) -> SessionRepository: ...

    @property
    def email_tokens(self) -> EmailTokenRepository: ...

    @property
    def accounts(self) -> AccountRepository: ...

    @property
    def memberships(self) -> MembershipRepository: ...

    @property
    def invitations(self) -> InvitationRepository: ...

    @property
    def api_keys(self) -> ApiKeyRepository: ...

    @property
    def domains(self) -> DomainRepository: ...

    @property
    def dkim_keys(self) -> DkimKeyRepository: ...

    @property
    def sender_identities(self) -> SenderIdentityRepository: ...

    @property
    def assets(self) -> AssetRepository: ...

    @property
    def messages(self) -> MessageRepository: ...

    @property
    def outbox(self) -> OutboxRepository: ...

    @property
    def delivery(self) -> DeliveryRepository: ...

    @property
    def suppressions(self) -> SuppressionRepository: ...

    @property
    def audit(self) -> AuditRepository: ...

    @property
    def rate_limits(self) -> RateLimitRepository: ...

    @property
    def sync(self) -> SyncRepository: ...

    @property
    def exports(self) -> ExportRepository: ...

    @property
    def jobs(self) -> JobRepository: ...


    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def savepoint(self) -> Any: ...
